// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWXrjoOpBlTEm-1fa3W3MV26EtsV-Cvig',
    appId: '1:646480940726:web:fc9683cee0f8fd1a986017',
    messagingSenderId: '646480940726',
    projectId: 'myfirebase-86444',
    authDomain: 'myfirebase-86444.firebaseapp.com',
    databaseURL: 'https://myfirebase-86444-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirebase-86444.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOHBbRJnoZ2yGk1L8a_KAYqMMABlpEQAo',
    appId: '1:646480940726:android:d74168a01049ad3f986017',
    messagingSenderId: '646480940726',
    projectId: 'myfirebase-86444',
    databaseURL: 'https://myfirebase-86444-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirebase-86444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPIKEaRafqJLlK2j14KY-_ActUtET5tk',
    appId: '1:646480940726:ios:47d77563efa50df8986017',
    messagingSenderId: '646480940726',
    projectId: 'myfirebase-86444',
    databaseURL: 'https://myfirebase-86444-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirebase-86444.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPIKEaRafqJLlK2j14KY-_ActUtET5tk',
    appId: '1:646480940726:ios:79be02f5530276dc986017',
    messagingSenderId: '646480940726',
    projectId: 'myfirebase-86444',
    databaseURL: 'https://myfirebase-86444-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirebase-86444.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
